<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 1.1.14 */
/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.directive('autoremove', (el, { value, expression }, { evaluate }) => {
            if (expression) {
                const timeout = evaluate(expression);
                const messageType = el.getAttribute('data-message-type');
                const messageText = el.getAttribute('data-message-text');
                setTimeout(() => {
                    Alpine.store('Message').removeMessage(messageType, messageText);
                }, timeout);
            }
        });
    });
</script>
