<?php
declare(strict_types=1);

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 1.1.15 */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var CssClass $css */
/** @var Exception $exception */

?>
<details>
    <summary><?= $escaper->escapeHtml($block->getMessage()) ?></summary>
    [<?= $escaper->escapeHtml($block->getFile()) ?> line <?= (int)$block->getLine() ?>]<br/>
    <code class="<?= $escaper->escapeHtml($css('block mt-4 text-sm', 'trace')) ?>">
        <?php foreach ($block->getTrace() as $trace): ?>
            <?= $escaper->escapeHtml($trace) ?><br/>
        <?php endforeach; ?>
    </code>
</details>
