<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @version 1.0.4 */
/** @var Template $block */

$timeout = (int)$block->getTimeout(); // @todo Right source for this?
if (!$timeout > 0) {
    $timeout = 100000;
}
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiMessagesComponent', () => ({
            messages: [],
            timeout: <?= (int)$timeout ?>,
            init() {
                Alpine.effect(() => {
                    this.messages = Alpine.store('LokiMessageStore').getMessages();
                });
            },
            hasMessages() {
                return this.messages.length > 0;
            },
            removeMessage() {
                const type = this.$el.getAttribute('data-message-type');
                const text = this.$el.getAttribute('data-message-text');
                Alpine.store('LokiMessageStore').removeMessage(type, text);
            },
        }));
    });
</script>
