<?php
declare(strict_types=1);

use Loki\Base\Config\Config;
use Loki\Base\ViewModel\ModuleConfig;
use Magento\Framework\View\Element\Template;

/** @version 1.1.15 */
/** @var Template $block */
/** @var Config $config */
/** @var ModuleConfig $moduleConfig */

$moduleConfig = $block->getModuleConfig();
if ($moduleConfig->isEnabled('MageOS_AlpineMessages')) {
    return;
}

$timeout = $block->getTimeout();
if (false === is_numeric($timeout) || $timeout < 0) {
    $config = $block->getConfig();
    $timeout = $config->getMessagesTimeout();
}
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiMessagesComponent', () => ({
            messages: [],
            timeout: <?= (int)$timeout ?>,
            init() {
                Alpine.effect(() => {
                    this.messages = Alpine.store('Message').getMessages();
                    console.log('Foobar1 reading', JSON.parse(JSON.stringify(this.messages)));
                });
            },
            hasMessages() {
                return this.messages.length > 0;
            },
            removeMessage() {
                const type = this.$el.getAttribute('data-message-type');
                const text = this.$el.getAttribute('data-message-text');
                Alpine.store('Message').removeMessage(type, text);
            },
        }));
    });
</script>
