<?php
declare(strict_types=1);

use Loki\Theme\ViewModel\CookieConfig;
use Magento\Framework\View\Element\Template;

/** @version 0.0.6 */
/** @var Template $block */
/** @var CookieConfig $cookieConfig */

$cookieConfig = $block->getCookieConfig();
?>
<script>
    const LokiCookies = {
        lifetime: <?= /* @noEscape */ $cookieConfig->getLifetime() ?>,
        domain: '<?= /* @noEscape */ $cookieConfig->getDomain() ?>',
        path: '<?= /* @noEscape */ $cookieConfig->getPath() ?>',
        httpOnly: <?= /* @noEscape */ $cookieConfig->isHttpOnly() ?>,
        sameSite: '<?= /* @noEscape */ $cookieConfig->getSameSite() ?>',
        getAll() {
            const cookies = {};
            document.cookie.split(';').forEach(cookie => {
                const parts = cookie.split('=');
                const name = parts[0].trim();
                let value = parts[1].trim();

                value = decodeURI(value);
                value = decodeURIComponent(value);
                if (value.startsWith('{') && value.endsWith('}')) {
                    value = JSON.parse(value);
                }

                cookies[name] = value;
            })

            return cookies;
        },
        get(name) {
            return this.getAll()[name];
        },
        set(name, value) {
            let cookieParts = [];
            cookieParts.push(name + '=' + value);
            cookieParts.push('max-age=' + this.lifetime + 20000);

            if (this.path) {
                cookieParts.push('path=' + this.path);
            }

            if (this.domain) {
                cookieParts.push('domain=' + this.domain);
            }

            if (this.httpOnly) {
                cookieParts.push('secure');
            }

            cookieParts.push('SameSite=' + this.sameSite);
            console.log('set cookie', cookieParts);

            document.cookie = cookieParts.join('; ');
        },
        isAllowedSaving() {
            return this.get('user_allowed_save_cookie');
        }
    }
</script>
