<?php
declare(strict_types=1);

use Loki\Base\ViewModel\FormKeyValue;
use Magento\Framework\View\Element\Template;

/** @version 0.0.6 */
/** @var Template $block */
/** @var FormKeyValue $formKeyValue */

$formKeyValue = $block->getFormKeyValue();
?>
<script>
    var LOKI_BASE_URL = '<?= /* @noEscape */ $block->getBaseUrl() ?>';
    var LOKI_FORM_KEY = '<?= /* @noEscape */ $formKeyValue->get() ?>';
</script>
