<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiMessagesComponent', () => ({
            messages: [],
            init() {
                Alpine.effect(() => {
                    this.messages = Alpine.store('LokiMessageStore').getMessages();
                });
            },
            hasMessages() {
                return this.messages.length > 0;
            },
            removeMessage() {
                const messageText = this.$el.getAttribute('data-message-text');
                Alpine.store('LokiMessageStore').removeMessage(messageText);
            },
            onLoadDirective(args) {
                console.log('onLoadDirective', this.$el, args);
            }
        }));
    });
</script>
