<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiMessagesComponent', () => ({
            messages: [],
            init() {
                Alpine.effect(() => {
                    this.messages = Alpine.store('LokiMessageStore').getMessages();
                    Alpine.store('LokiMessageStore').reset();
                });
            },
            hasMessages() {
                return this.messages.length > 0;
            },
            removeMessage() {
                this.$el.style.display = 'none'
            }
        }));
    });
</script>
