<?php
declare(strict_types=1);

use Loki\Base\ViewModel\FormKeyValue;
use Loki\Base\ViewModel\LocaleCode;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 1.1.11 */
/** @var Template $block */
/** @var FormKeyValue $formKeyValue */
/** @var LocaleCode $localeCode */
/** @var Escaper $escaper */

$formKeyValue = $block->getFormKeyValue();
$localeCode = $block->getLocaleCode();
$mobileWidth = $block->getMobileWidth();
if (!is_numeric($mobileWidth) || $mobileWidth < 100) {
    $mobileWidth = 767;
}
?>
<script>
    var BASE_URL = '<?= $escaper->escapeUrl($block->getBaseUrl()) ?>';
    var LOKI_LOCALE = '<?= $escaper->escapeUrl($localeCode->getCode()) ?>';
    var LOKI_THEME_URL = '<?= $escaper->escapeUrl($block->getViewFileUrl('')) ?>';
    var LOKI_FORM_KEY = '<?= $escaper->escapeHtml($formKeyValue->get()) ?>';
    var LOKI_CURRENT_URL = window.location.href.split('?')[0];
    var LOKI_IS_MOBILE = ((window.innerWidth > 0) ? window.innerWidth : screen.width) < <?= (int)$mobileWidth ?>; // @todo: What happens if you change browser width on the fly?
</script>
