<?php
declare(strict_types=1);

/** @version 1.0.1 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.directive('autoremove', (el, { value, expression }, { evaluate }) => {
            if (expression) {
                const timeout = evaluate(expression);
                const messageText = el.getAttribute('data-message-text');
                setTimeout(() => {
                    Alpine.store('LokiMessageStore').removeMessage(messageText);
                }, timeout);
            }
        });
    });
</script>
